--1)	Create a sequence by name EMPID_SEQ starting with value 100 with an interval of 1.
create database exp_8
GO
USE exp_8
GO
CREATE SCHEMA EMPLOYEE ;
GO
CREATE SEQUENCE EMPLOYEE.EMPID_SEQ  
    START WITH 100 
    INCREMENT BY 1 ; 
GO
--2)	Write a SQL command for finding the current and the next status of  EMPID_SEQ.
SELECT NEXT VALUE FOR EMPLOYEE.EMPID_SEQ  /*EXECUTE THIS STATMENT THREE TIME*/
GO
--3)	Change the Cache value of the sequence EMPID_SEQ to 20 and maxvalue to 1000.
ALTER SEQUENCE EMPLOYEE.EMPID_SEQ 
    RESTART WITH 500  
    INCREMENT BY 5 
    MINVALUE 50  
    MAXVALUE 1000  
    CYCLE  
    CACHE 20   
GO  
SELECT NEXT VALUE FOR EMPLOYEE.EMPID_SEQ 
GO
--4)	Insert values in employees table using sequences for employee_id column.
CREATE SCHEMA TEST;
GO

CREATE TABLE TEST.EMPLOYEE
( 
EMPID INTEGER PRIMARY KEY, 
ENAME VARCHAR(30),
JOB VARCHAR(20),
MGR INTEGER,
HIREDATE  DATE, 
SAL INTEGER,
COMM INTEGER,
DEPTNO INTEGER
)
GO
CREATE SEQUENCE TEST.emp_id
    START WITH 1000  
    INCREMENT BY 1 ;  
GO  


INSERT TEST.EMPLOYEE (EMPID, ENAME, JOB,MGR, HIREDATE,SAL,COMM,DEPTNO) values (NEXT VALUE FOR TEST.emp_id, 'ALLEN','SALESMAN', 7698,'20-FEB-81',1600,300,30)
GO
SELECT * FROM TEST.EMPLOYEE 
GO
INSERT TEST.EMPLOYEE (EMPID, ENAME, JOB,MGR, HIREDATE,SAL,COMM,DEPTNO) values (NEXT VALUE FOR TEST.emp_id, 'WARD',  'SALESMAN',7698, '22-FEB-81', 1250,500,30)
GO
SELECT * FROM TEST.EMPLOYEE 
---5)	Drop sequence EMPID_SEQ. 
DROP SEQUENCE EMPLOYEE.EMPID_SEQ
GO
---6)	Create a sequence called REVERSE to generate numbers in the descending order from 10000 to 1000 with a decrement of 5.
CREATE SEQUENCE TEST.REVERSE
    START WITH 10000 
    INCREMENT BY -5 
	MINVALUE 1000  
    MAXVALUE 10000  
    CYCLE  
    CACHE 3 
	GO
	SELECT NEXT VALUE FOR TEST.REVERSE
